// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjnldbefvzmqwzljkgzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qbmxkYmVmdnptcXd6bGprZ3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MjU1NDgsImV4cCI6MjA2NjMwMTU0OH0.oRZpwXVMeOfTbV8ylWBYIdIBQyUTVnkwf1SAIZUiN2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);